[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "*"
common = { version = "*", path="../common" }
num-traits = "*"
console_error_panic_hook = "0.1.7"
