[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]

derive_macro = { path = "../derive-macro/" }
num-derive = "*"
num-traits = "*"
bevy_rapier2d = { version = "*", optional = true }

[features]
server = ["dep:bevy_rapier2d"]